export const ActionTypes  = {
  SET_LOADING:"SET_LOADING",
  SET_PRODUCTS:"SET_PRODUCTS",
  SET_ERROR:"SET_ERROR",

  SET_CART_LOADING:"SET_CART_LOADING",
  SET_CART:"SET_CART",
  SET_CART_ERROR:"SET_CART_ERROR",
  ADD_TO_CART:"ADD_TO_CART",
  UPDATE_ITEM:"UPDATE_ITEM",
  REMOVE_ITEM:"REMOVE_ITEM",
}